/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/admin.vue')['default']
    AdminReturnButton: typeof import('./src/components/AdminReturnButton.vue')['default']
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessModal: typeof import('./src/components/SuccessModal.vue')['default']
    TiptapEditor: typeof import('./src/components/TiptapEditor.vue')['default']
    VerificationCodeModal: typeof import('./src/components/VerificationCodeModal.vue')['default']
  }
}
